### ISSUE TITLE
Manifest.json at Head

### ISSUE THREAD

**Issue by LuwkasLima** [colinhemphill/nextjs-resume#219]
Hi, I noticed that there isn't a manifest.json reference to Next JS app Head: "link rel="manifest" href="/manifest.json". Is that on purpose? Happy to quickly suggest the update as part of the DefaultTags.

**Comment by colinhemphill** [comment]
The manifest was only there to support PWA which I've long since removed. Moving forward I'm using the [Metadata API](https://beta.nextjs.org/docs/api-reference/metadata) and reading from `resumeConfig`, so this won't be needed for anything. Will remove it in the next version!
