### ISSUE TITLE
Word hyphenation is not idea for resume scanning algorithms

### ISSUE THREAD

**Issue by justin-hackin** [colinhemphill/nextjs-resume#232]
`react-pdf` hyphenates words for wrapping purposes by default. I'm removing this as demonstrated [here in the docs](https://react-pdf.org/fonts#disabling-hyphenation).

**Comment by colinhemphill** [comment]
@justin-hackin that was already removed in 3.1.0

https://github.com/colinhemphill/nextjs-resume/blob/main/CHANGELOG.md#changed-2

**Comment by justin-hackin** [comment]
Whoops, I should probably take a look at that to see what other improvements I can glean, thanks.
