### ISSUE TITLE
Incompatible with Night Eye Chrome extension

### ISSUE THREAD

**Issue by justin-hackin** [colinhemphill/nextjs-resume#239]
Irrespective of which `prefers-color-scheme` value is set, the site contains some text that is very low contrast (though the low-contrast text varies based on light/dark) when the Night Eye Chrome extension is active. For this reason, I'm going to switch to using underline for emphasis.

**Comment by colinhemphill** [comment]
I don't think there's anything actionable here, so best I can give you is 👍 I don't intend to make any changes to support third-party stuff.
