### ISSUE TITLE
Warning: Bun is used as a package manager at build time only, not at runtime with Functions

### ISSUE THREAD

**Issue by mahmoude4477** [colinhemphill/nextjs-resume#374]
i Deploy project to vercel and the error is Warning: Bun is used as a package manager at build time only, not at runtime with Functions

**Comment by colinhemphill** [comment]
@mahmoude4477 That is expected as Vercel only uses Bun for installations at this time. As long as it's a warning it won't be a problem.

If your deploy is failing, it is not related to this message.
