### ISSUE TITLE
.nvmrc would be helpful!

### ISSUE THREAD

**Issue by rachelslurs** [colinhemphill/nextjs-resume#466]
![Screenshot 2024-02-16 at 12 51 27 PM](https://github.com/colinhemphill/nextjs-resume/assets/1870406/676568a1-4605-445a-9327-cda17793f1fd)

Also, I absolutely love this project @colinhemphill! Thank you for sharing. The PDF generator API works like magic!

**Comment by colinhemphill** [comment]
@rachelslurs Added! I went for `lts/*` since that should always target something compatible with Next and Vercel.
