### ISSUE TITLE
Private fields not showing up

### ISSUE THREAD

**Issue by ImranArtwel** [colinhemphill/nextjs-resume#518]
I have added a private field of email in this format:

```
-----
label: xxx
-----

abb@gmail.com
```

but it wont show up. i have added private key in the env

**Comment by colinhemphill** [comment]
@ImranArtwel Are you viewing the resume at the private link? Those fields won't show up at the root of the app. You can see it working in the example repo here:

https://nextjs-tailwind-resume.vercel.app/private/64875f6c-7ddc-4159-ad1f-f91211ece8b8
